### ISSUE TITLE
How did you learn this?

### ISSUE THREAD

**Issue by andygrunwald** [wichtounet/thor-os#1]
Hey,

i came across this OS and i am impressed.
You created this for learning reasons, but i ask myself: 
- What did you read? 
- Where do you learn those things?

It might be interesting (for others as well) to know your learning why, how you got into this and how others can do the same way.
A small chapter in the readme about this might be cool and helpful for others (even motivating!)

**Comment by wichtounet** [comment]
Hello Andy, 

This is an excellent idea :)

I'll do that tomorrow either on the Wiki or on the Readme and I'll update this issue when done.

**Comment by wichtounet** [comment]
Hi, 

I've a added a few information to the readme as to the why and to the how of this project. 

Hope this answers your questions ;) Otherwise, feel free to ask more ;)

**Comment by andygrunwald** [comment]
Thank you Baptiste!
This is great and enough resources to read for the next two month :)
And thank you for this quick answer and the immediate action. As i can guess from the added reactions to this issue, many people loved to read things like this.

From my side you helped me a lot. I will close it. Have a nice day!
PS: Good work and you started a process of thinking in my head to do the same (but maybe start with a compiler itself ;))

**Comment by darxtrix** [comment]
Hi, 

Great work ! It would be great if you can create something like this : https://github.com/SamyPesse/How-to-Make-a-Computer-Operating-System . I understand that it would take good amount of time but its worth it :smile:

**Comment by wichtounet** [comment]
Hi @black-perl, 

This is something I want to do on my blog with a series of post building a small OS step by step, but I will probably only start this once Thor is in better shape. I cannot give any ETA for now ;)

**Comment by darxtrix** [comment]
Sure,  we will be waiting for this. Good luck.
