### ISSUE TITLE
Prompt command display issue

### ISSUE THREAD

**Issue by landyde** [wichtounet/thor-os#13]
Hello,

![image](https://user-images.githubusercontent.com/3834189/39672388-ac4a9d02-5129-11e8-9d52-3d5b98d51b32.png)

It's been a week I'm trying to compile and launch your os, I succeeded !
but I'm in front of a screen without the command prompt, do you know what could be the issue ?

This is the current virtual.log after one execution :
PAE Activated
Paging configured
Long mode enabled
PML4T set
Paging enabled
partition_start: 2048
sectors_per_cluster: 8
reserved_sectors: 32
number_of_fat: 2
sectors_per_fat: 984
root_dir_start: 2
fat_begin: 2080
cluster_begin: 4048
entries_per_cluster: 128
kernel_cluster_first: 9
kernel_size: 569948
Number of clusters read for kernel: 140
TRACE:0: 7 early logs
EARLY: A20 gate enabled
EARLY: Interrupts disabled
EARLY: PAE Activated
EARLY: Paging configured
EARLY: Long mode enabled
EARLY: PML4T set
EARLY: Paging enabled
TRACE:0: int: IDT installed 0x16F950 (base:0x16F960)
TRACE:0: Kernel occupies 1 MiB from 0x100000
TRACE:0: paging: early_init (virtual_paging_start:0x200000)
TRACE:0: paging: init (physical_memory:0x200000, physical_pages:515)
TRACE:0: paging: PML4T entries:1 phys:0x200000 virt:0x200000
TRACE:0: paging: PDPT entries:1 phys:0x201000 virt:0x201000
TRACE:0: paging: PD entries:512 phys:0x202000 virt:0x202000
TRACE:0: paging: PT entries:262144 phys:0x203000 virt:0x203000
TRACE:0: paging: Set 0x200000 (physical) as new CR3
TRACE:0: paging: basic tests
TRACE:0: paging: basic tests finished
TRACE:0: palloc: Buddy allocator in place
TRACE:0: palloc: Managed space 123MiB
TRACE:0: palloc: Level 0 496 blocks
TRACE:0: palloc: Level 1 248 blocks
TRACE:0: palloc: Level 2 124 blocks
TRACE:0: palloc: Level 3 62 blocks
TRACE:0: palloc: Level 4 31 blocks
TRACE:0: palloc: Level 5 16 blocks
TRACE:0: palloc: Level 6 8 blocks
TRACE:0: palloc: Level 7 4 blocks
TRACE:0: vesa_console: init()
TRACE:0: vesa_console: Buffer size: 5MiB
DEBUG:0: stdio: using 3 terminals
DEBUG:0: timer: Unable to install HPET driver
DEBUG:0: timer: Frequency set to 1000 Hz
DEBUG:0: scheduler:: Frequency updated. New Round Robin quantum: 25
TRACE:0: PIT Driver Installed
TRACE:0: mouse: PS/2 mouse driver installed
TRACE:0: ata: Identified disk of size: 516096000
TRACE:0: ata: Identified disk of size: 0
TRACE:0: ramdisk: Created ramdisk 0 of size 1MiB with 256 pages
DEBUG:0: Found device pci:0:0:0 (vendor:32902 class:6 subclass:0)
DEBUG:0: Found device pci:0:1:0 (vendor:32902 class:6 subclass:1)
DEBUG:0: Found device pci:0:1:1 (vendor:32902 class:1 subclass:1)
DEBUG:0: Found device pci:0:1:3 (vendor:32902 class:6 subclass:128)
DEBUG:0: Found device pci:0:2:0 (vendor:4660 class:3 subclass:0)
DEBUG:0: Found device pci:0:3:0 (vendor:4332 class:2 subclass:0)
TRACE:0: rtl8139: Initialize RTL8139 driver on pci:0:3:0
TRACE:0: rtl8139: I/O Base address :0xC000
TRACE:0: rtl8139: Physical RX Buffer :0x417000
TRACE:0: rtl8139: Virtual RX Buffer :0x514000
TRACE:0: rtl8139: IRQ :11
TRACE:0: rtl8139: MAC Address 0x525400123456
TRACE:0: loopback: Initialize loopback driver
TRACE:0: vfs: mounted file system /dev/hda1/ at /
TRACE:0: vfs: mounted file system none/ at /sys/
TRACE:0: vfs: mounted file system none/ at /dev/
TRACE:0: vfs: mounted file system none/ at /proc/
TRACE:0: fat32: Number of fat:2
DEBUG:0: scheduler: idle_task 0
DEBUG:0: scheduler: init_task 1 tty:0 fd:/dev/tty0
DEBUG:0: scheduler: init_task 2 tty:1 fd:/dev/tty1
DEBUG:0: scheduler: init_task 3 tty:2 fd:/dev/tty2
DEBUG:0: scheduler: gc_task 4
DEBUG:0: scheduler: post_init_task 5
TRACE:0: scheduler: initialized (PCB size:43KiB pcb_entry:344B process: 192B)

Thxs
Dylan

**Comment by wichtounet** [comment]
Hello Dylan, 

Sorry it took you so long to compile and run it. 

That is weird, the log seems correct except that the shell does not seem to be started..

You started with `make qemu` ?
You are using the develop branch ?

**Comment by landyde** [comment]
Hello,

I think the old version of GCC create conflicts with new libraries that's why it was difficult to compile GCC for cross compilation, I had a lot of errors.

Yes ... I don't understand, maybe my kernel version, this is one of the things I haven't checked yet.
I thought hopefully you might have already had that mistake!

I will continue to investigate and if you have anything on it I'm a catcher.

Thx
Dylan

**Comment by ghatzz** [comment]
how can I run the os

**Comment by wichtounet** [comment]
> how can I run the os

https://github.com/wichtounet/thor-os/wiki/Build
