### ISSUE TITLE
Why TSTL?

### ISSUE THREAD

**Issue by adminy** [wichtounet/thor-os#15]
I can't use anything from tstl, so why have it there? Also There are lots of things you can't include by default, can you add all the string functions at least? (optionally a map) Thank you.

(PS: shutdown program not working at all, does nothing.)

**Comment by wichtounet** [comment]
Hello, 

The TSTL is to replace the STL from the C++ language. The STL is not portable. Therefore, I add to reimplement what I needed. It's only made to be used from inside the kernel or from programs made for my kernel. 

What do you mean you can't use anything from TSTL ? 

Yes, I know the shutdown program is broken :S
