### ISSUE TITLE
Run on raspberry pi, arduino?

### ISSUE THREAD

**Issue by igolden** [wichtounet/thor-os#2]
This looks great. Congrats on knocking this out.

You get this up and running on a raspberry pi or arduino? I'd like to make a project of it, and it could be helpful to others to throw something in the README.

Cheers!

**Comment by G07cha** [comment]
@igolden the description says that this OS for 64-bit processors when Raspberry Pi based on ARM processor and Arduino is a microcontroller. So there is a lot of work needed to make it work on this platforms.

**Comment by wichtounet** [comment]
Hi, 

Thanks :)

Indeed, for now there is only support for Intel x86_64 architecture. It would be a lot of work to make it work on an ARM platform. For now, I have no plan on doing that, but that could be an interesting project to tackle :)

Baptiste

**Comment by krglaws** [comment]
Would this run in the Bochs x86 emulator by any chance?

**Comment by wichtounet** [comment]
It does run on Bochs as long as your Bochs is able to emulate x86_64. It will not work on 32 bits x86.
