### ISSUE TITLE
Unable to display os ui

### ISSUE THREAD

**Issue by landyde** [wichtounet/thor-os#20]
Hello,

I tried to launch your os, there are no errors during compilation, when I execute on qemu and press enter it stays like displayed on this screen. Do you have any idea?

The virtual.log is empty.

Thank you,
Dylan

![image](https://user-images.githubusercontent.com/3834189/58211023-0ab05d80-7ceb-11e9-8959-7be8e8137d1c.png)

**Comment by wichtounet** [comment]
Hi Dylan, 

Sorry for the huge delay :( 

Like this, no I have no idea. I have not worked on this project for months now. It's in a dormant state and I do not have time to investigate new issues, sorry :(
