### ISSUE TITLE
qemu-system-x86_64: brigde helper failed

### ISSUE THREAD

**Issue by lobakkang** [wichtounet/thor-os#24]
![image](https://user-images.githubusercontent.com/33191745/75227520-557c6b80-577c-11ea-9f14-91a7d27ad14d.png)
what should it do?

**Comment by wichtounet** [comment]
I am guessing that Qemu change options and that this does not work anymore
with recent versions of Qemu. For now, I do not have time to install Qemu
and try it. But I will try to do that next month.

Keep in mind that I have not been working on this project for years so many
things may be outdated.

**Comment by lobakkang** [comment]
I try to change the command to :
sudo qemu-system-x86_64 -enable-kvm -cpu host -serial file:virtual.log -vga std -hda hdd.img
It run but stuck at bootloader.
![image](https://user-images.githubusercontent.com/33191745/75754922-98e65500-5cfb-11ea-8833-1f96707d79f5.png)

**Comment by subinacl** [comment]
There is an issue with the init.bin entry_point.
Still don't understand the root of the issue, but was able to WAR it by adding:
void  __attribute__ ((noreturn)) rm_main();
void  __attribute__ ((noreturn)) foo(){  rm_main(); }
Right after includes in the boot_16.cpp.

**Comment by lobakkang** [comment]
Thanks it work!!!
not add:
void attribute ((noreturn)) rm_main();
void attribute ((noreturn)) foo(){ rm_main(); }

FIX:
void attribute __((noreturn)) __ rm_main();
void attribute __((noreturn)) __ foo() { rm_main(); }

Thanks ;D

**Comment by wichtounet** [comment]
> There is an issue with the init.bin entry_point.
> Still don't understand the root of the issue, but was able to WAR it by
adding:
> void **attribute** ((noreturn)) rm_main();
> void **attribute** ((noreturn)) foo(){ rm_main(); }
> Right after includes in the boot_16.cpp.

Wow, that must be something weird with the new compiler. I will have to
check this out. I would think that the rm_main symbol is removed.

Thanks for providing a fix :)
