### ISSUE TITLE
Failed to read cluster from disk

### ISSUE THREAD

**Issue by lobakkang** [wichtounet/thor-os#31]
Recently, I moved thor os from Linux dual boot to wsl2. At first, everything worked fine but I realize that the OS is frequently failed to boot. Then, I boot it 5 times and list out the log.

virtual.log:

//1
PAE Activated
Paging configured
Long mode enabled
PML4T set
Paging enabled
partition_start: 2048
sectors_per_cluster: 8
reserved_sectors: 32
number_of_fat: 2
sectors_per_fat: 984
root_dir_start: 2
fat_begin: 2080
cluster_begin: 4048
entries_per_cluster: 128
kernel_cluster_first: 9
kernel_size: 570316
stopped at:7 <-- I added a line of code to know where it stopped
Failed to read cluster from disk

//2
PAE Activated
Paging configured
Long mode enabled
PML4T set
Paging enabled
partition_start: 2048
sectors_per_cluster: 8
reserved_sectors: 32
number_of_fat: 2
sectors_per_fat: 984
root_dir_start: 2
fat_begin: 2080
cluster_begin: 4048
entries_per_cluster: 128
kernel_cluster_first: 9
kernel_size: 570316
stopped at:35
Failed to read cluster from disk

//3
PAE Activated
Paging configured
Long mode enabled
PML4T set
Paging enabled
partition_start: 2048
sectors_per_cluster: 8
reserved_sectors: 32
number_of_fat: 2
sectors_per_fat: 984
root_dir_start: 2
fat_begin: 2080
cluster_begin: 4048
entries_per_cluster: 128
kernel_cluster_first: 9
kernel_size: 570316
stopped at:46
Failed to read cluster from disk

//4 - this time it scussfully boot
PAE Activated
Paging configured
Long mode enabled
PML4T set
Paging enabled
partition_start: 2048
sectors_per_cluster: 8
reserved_sectors: 32
number_of_fat: 2
sectors_per_fat: 984
root_dir_start: 2
fat_begin: 2080
cluster_begin: 4048
entries_per_cluster: 128
kernel_cluster_first: 9
kernel_size: 570316
Number of clusters read for kernel: 140
TRACE:0: 7 early logs 
EARLY: A20 gate enabled
EARLY: Interrupts disabled
EARLY: PAE Activated
EARLY: Paging configured
EARLY: Long mode enabled
EARLY: PML4T set
EARLY: Paging enabled
TRACE:0: int: IDT installed 0x16F9C0 (base:0x16F9E0)
TRACE:0: Kernel occupies 1 MiB from 0x100000
TRACE:0: paging: early_init (virtual_paging_start:0x200000)
TRACE:0: paging: init (physical_memory:0x200000, physical_pages:515)
TRACE:0: paging: PML4T entries:1 phys:0x200000 virt:0x200000
TRACE:0: paging: PDPT entries:1 phys:0x201000 virt:0x201000
TRACE:0: paging: PD entries:512 phys:0x202000 virt:0x202000
TRACE:0: paging: PT entries:262144 phys:0x203000 virt:0x203000
TRACE:0: paging: Set 0x200000 (physical) as new CR3
TRACE:0: paging: basic tests
TRACE:0: paging: basic tests finished
TRACE:0: palloc: Buddy allocator in place
TRACE:0: palloc: Managed space 123MiB
TRACE:0: palloc: Level 0 496 blocks
TRACE:0: palloc: Level 1 248 blocks
TRACE:0: palloc: Level 2 124 blocks
TRACE:0: palloc: Level 3 62 blocks
TRACE:0: palloc: Level 4 31 blocks
TRACE:0: palloc: Level 5 16 blocks
TRACE:0: palloc: Level 6 8 blocks
TRACE:0: palloc: Level 7 4 blocks
TRACE:0: vesa_console: init()
TRACE:0: vesa_console: Buffer size: 1MiB
DEBUG:0: stdio: using 3 terminals
DEBUG:0: timer: Unable to install HPET driver
DEBUG:0: timer: Frequency set to 1000 Hz
DEBUG:0: scheduler:: Frequency updated. New Round Robin quantum: 25
TRACE:0: PIT Driver Installed
TRACE:0: mouse: PS/2 mouse driver installed
TRACE:0: ata: Identified disk of size: 516096000 
TRACE:0: ata: Identified disk of size: 0 
TRACE:0: ramdisk: Created ramdisk 0 of size 1MiB with 256 pages
DEBUG:0: Found device pci:0:0:0 (vendor:32902 class:6 subclass:0) 
DEBUG:0: Found device pci:0:1:0 (vendor:32902 class:6 subclass:1) 
DEBUG:0: Found device pci:0:1:1 (vendor:32902 class:1 subclass:1) 
DEBUG:0: Found device pci:0:1:3 (vendor:32902 class:6 subclass:128) 
DEBUG:0: Found device pci:0:2:0 (vendor:4660 class:3 subclass:0) 
DEBUG:0: Found device pci:0:3:0 (vendor:32902 class:2 subclass:0) 
TRACE:0: loopback: Initialize loopback driver
TRACE:0: vfs: mounted file system /dev/hda1/ at /
TRACE:0: vfs: mounted file system none/ at /sys/
TRACE:0: vfs: mounted file system none/ at /dev/
TRACE:0: vfs: mounted file system none/ at /proc/
TRACE:0: fat32: Number of fat:2
DEBUG:0: scheduler: idle_task 0 
DEBUG:0: scheduler: init_task 1 tty:0 fd:/dev/tty0
DEBUG:0: scheduler: init_task 2 tty:1 fd:/dev/tty1
DEBUG:0: scheduler: init_task 3 tty:2 fd:/dev/tty2
DEBUG:0: scheduler: gc_task 4 
DEBUG:0: scheduler: post_init_task 5 
TRACE:0: scheduler: initialized (PCB size:43KiB pcb_entry:344B process: 192B)
TRACE:0: Allocations before start of scheduler: 247
TRACE:0: scheduler: starting
DEBUG:5: scheduler: post_init_task (pid:5) started 3 tasks
DEBUG:5: acpi: Started initialization of ACPICA
DEBUG:5: ACPICA started initialization
TRACE:5: acpica: ACPI Root pointer found at physical address 0xF58D0
TRACE:5: ACPI: TRACE:5: RSDP 0x                        (v00 6.6s)TRACE:5: 
TRACE:5: ACPI: TRACE:5: 4.4s 0x                        (v5479780 6.6s 8.8s          4.4s         )TRACE:5: 
TRACE:5: ACPI: TRACE:5: 4.4s 0x                        (v5479604 6.6s 8.8s          4.4s         )TRACE:5: 
TRACE:5: ACPI: TRACE:5: 4.4s 0x                        (v5479620 6.6s 8.8s          4.4s         )TRACE:5: 
TRACE:5: ACPI: TRACE:5: 4.4s 0x                       TRACE:5: 
TRACE:5: ACPI: TRACE:5: 4.4s 0x                        (v5479604 6.6s 8.8s          4.4s         )TRACE:5: 
TRACE:5: ACPI: TRACE:5: 4.4s 0x                        (v5479604 6.6s 8.8s          4.4s         )TRACE:5: 
TRACE:5: 
Initializing Namespace objects:
TRACE:5: Table [DSDT: 8.8s] (id ) - 5914704 Objects with 1   Devices, 285 Regions, 53   Methods (8/75/12 Serial/Non/Cvt)
TRACE:5: ACPI: TRACE:5: 1 ACPI AML tables successfully acquired and loaded
TRACE:5: 
TRACE:5: Completing Region/Field/Buffer/Package initialization:
TRACE:5:     Initialized 8/8 Regions 0/0 Fields 20/20 Buffers 4/4 Packages (294 nodes)
TRACE:5: Initializing Device/Processor/Thermal objects and executing _INI/_STA methods:
TRACE:5:     Executed 1 _INI methods requiring 0 _STA executions (examined 56 objects)
DEBUG:5: acpi: Finished initialization of ACPICA
TRACE:5: hpet: Found ACPI HPET table
TRACE:5: hpet: HPET Address: 0xFED00000
TRACE:5: hpet: HPET Capabilities: 0b110011000100101101000000010000000100001101010001000000001
TRACE:5: hpet: Late install suceeded
TRACE:5: hpet: period 10000000
TRACE:5: hpet: frequency 100000000Hz
TRACE:5: hpet: IRQ frequency 10000Hz
TRACE:5: hpet: Comparator update 10000
DEBUG:5: timer: Frequency set to 10000 Hz
DEBUG:5: scheduler:: Frequency updated. New Round Robin quantum: 250
TRACE:5: PIT Driver Removed
DEBUG:5: scheduler: post_init_task finished 3 tasks
DEBUG:5: scheduler: Kill 5
TRACE:6: network: RX Thread for interface 1 started (pid:6)
TRACE:7: network: TX Thread for interface 1 started (pid:7)
TRACE:8: stdio: Input Thread for terminal 0 started (pid:8)
TRACE:9: stdio: Input Thread for terminal 1 started (pid:9)
TRACE:10: stdio: Input Thread for terminal 2 started (pid:10)
DEBUG:1: scheduler: init_task started (pid:1)
TRACE:1: scheduler:exec: read_file start
TRACE:1: scheduler:exec: read_file end
DEBUG:1: scheduler: Process 11 cr3:0x4A7000
DEBUG:1: scheduler: Map(p11) virtual:0x8000700000 into phys: 0x4A9000
DEBUG:1: scheduler: Map(p11) virtual:0x8000400000 into phys: 0x4B7000
DEBUG:1: scheduler: Copy to physical:0x4B7000
DEBUG:1: scheduler: Map(p11) virtual:0x8000600000 into phys: 0x4BB000
DEBUG:1: scheduler: Copy to physical:0x4BB000
DEBUG:1: scheduler: Exec process pid=11, ppid=1
DEBUG:1: scheduler: Process 1 waits for 11
DEBUG:2: scheduler: init_task started (pid:2)
TRACE:2: scheduler:exec: read_file start
TRACE:2: scheduler:exec: read_file end
DEBUG:2: scheduler: Process 12 cr3:0x4B6000
DEBUG:2: scheduler: Map(p12) virtual:0x8000700000 into phys: 0x4C1000
DEBUG:2: scheduler: Map(p12) virtual:0x8000400000 into phys: 0x4C7000
DEBUG:2: scheduler: Copy to physical:0x4C7000
DEBUG:2: scheduler: Map(p12) virtual:0x8000600000 into phys: 0x4CB000
DEBUG:2: scheduler: Copy to physical:0x4CB000
DEBUG:2: scheduler: Exec process pid=12, ppid=2
DEBUG:2: scheduler: Process 2 waits for 12
DEBUG:3: scheduler: init_task started (pid:3)
TRACE:3: scheduler:exec: read_file start
TRACE:3: scheduler:exec: read_file end
DEBUG:3: scheduler: Process 13 cr3:0x4D1000
DEBUG:3: scheduler: Map(p13) virtual:0x8000700000 into phys: 0x4D3000
DEBUG:3: scheduler: Map(p13) virtual:0x8000400000 into phys: 0x4D7000
DEBUG:3: scheduler: Copy to physical:0x4D7000
DEBUG:3: scheduler: Map(p13) virtual:0x8000600000 into phys: 0x4DF000
DEBUG:3: scheduler: Copy to physical:0x4DF000
DEBUG:3: scheduler: Exec process pid=13, ppid=3
DEBUG:3: scheduler: Process 3 waits for 13

//5
PAE Activated
Paging configured
Long mode enabled
PML4T set
Paging enabled
partition_start: 2048
sectors_per_cluster: 8
reserved_sectors: 32
number_of_fat: 2
sectors_per_fat: 984
root_dir_start: 2
fat_begin: 2080
cluster_begin: 4048
entries_per_cluster: 128
kernel_cluster_first: 9
kernel_size: 570316
Unable to read FAT sector

Do you have any idea to solve it?
Thanks

**Comment by lobakkang** [comment]
I think I fix the issue. I use early log to debug and found that the problem is BSY flag cannot be clear. so I delete line 270, "return false" in boot32.cpp. This can let the bootloader ignore the flag but I don't know whether it has negative effect or not

**Comment by wichtounet** [comment]
Hi @felixthian 

Are you saying that you are testing on real hardware? I never tested thor-os outside of KVM or Bochs. It would be interesting to know how it does on real hardware. 

I think I understand the problem. This code is supposed to wait for up to 30 seconds, but it could much faster because it is not a real measure of time (just doing 30'000 times something that is supposed to last 400ns). 

In any case, in that case, this code is not really important because of the polling loop that will check BSY flag anyway. So, I do not think this will have negative effect. 

Thanks for reporting this :)
