### ISSUE TITLE
Documentation for tlib and tstl

### ISSUE THREAD

**Issue by CodeLongAndProsper90** [wichtounet/thor-os#34]
Would it be possible to get some basic documentation for the user-mode programs?
Just stuff for the system calls and tstl library?

Even just some comments in the code so that they can be added to the wiki

The topics I want most are:

* File, STD and Serial IO
* Input
* GLibC functions.

**Comment by wichtounet** [comment]
Hi, 

For the time being, I am not actively working on this project. So I will not be able to document it. But I will be sure to start with that when I start working on it again.
