### ISSUE TITLE
#include <acommon.h> missing

### ISSUE THREAD

**Issue by hackerman008** [wichtounet/thor-os#35]
trying to make ur project but getting error .
`include/acpica.hpp:18:10: fatal error: accommon.h: No such file or directory.`
`   18 | #include <accommon.h>
      |          ^~~~~~~~~~~~
compilation terminated.`

**Comment by wichtounet** [comment]
This is very likely because you have not initialized the submodules. 

Run this command into the thor-os director: `git submodule update --init`

And then try again.
