### ISSUE TITLE
the invalid option of "make -9" in Cross Compiler Wiki?

### ISSUE THREAD

**Issue by 2yz** [wichtounet/thor-os#4]
When I follow the Cross Compiler Wiki to execute the command "make -9", it go wrong.

`make: invalid option -- '9'`

I use Ubuntu 16.04 amd64.

**Comment by wichtounet** [comment]
Hi,

You're absolutely right. It was meant to be -j9 (use nine threads for compilation). 

This should be fixed in the wiki now. 

Thanks

Baptiste
