### ISSUE TITLE
Include file errors in acpica.hpp

### ISSUE THREAD

**Issue by definiteprogress** [wichtounet/thor-os#43]
$ make qemu
true
cd bootloader; make stage1.bin
make[1]: Entering directory '/home/monster/GitHub_projects/Reference_OS/thor-os-develop/bootloader'
make[1]: 'stage1.bin' is up to date.
make[1]: Leaving directory '/home/monster/GitHub_projects/Reference_OS/thor-os-develop/bootloader'
cd bootloader; make stage2.bin
make[1]: Entering directory '/home/monster/GitHub_projects/Reference_OS/thor-os-develop/bootloader'
make[1]: 'stage2.bin' is up to date.
make[1]: Leaving directory '/home/monster/GitHub_projects/Reference_OS/thor-os-develop/bootloader'
cd init; make
make[1]: Entering directory '/home/monster/GitHub_projects/Reference_OS/thor-os-develop/init'
make[1]: Nothing to be done for 'default'.
make[1]: Leaving directory '/home/monster/GitHub_projects/Reference_OS/thor-os-develop/init'
cd kernel; make
make[1]: Entering directory '/home/monster/GitHub_projects/Reference_OS/thor-os-develop/kernel'
[debug] Compile src/kernel_utils.cpp
[debug] Compile src/block_cache.cpp
[debug] Compile src/thor.cpp
[debug] Compile src/mmap.cpp
[debug] Compile src/vesa_console.cpp
[debug] Compile src/timer.cpp
[debug] Compile src/gdt.cpp
[debug] Compile src/acpi.cpp
In file included from src/acpi.cpp:8:
include/acpica.hpp:17:10: fatal error: acpi.h: No such file or directory
   17 | #include <acpi.h>
      |          ^~~~~~~~
compilation terminated.
make[1]: *** [Makefile:38: debug/src/acpi.cpp.o] Error 1
make[1]: Leaving directory '/home/monster/GitHub_projects/Reference_OS/thor-os-develop/kernel'
make: *** [Makefile:6: kernel/debug/kernel.bin] Error 2

**Comment by definiteprogress** [comment]
Please find the below 2 header files, which gives error while compiling with "make qemu"
//ACPICA
#include <acpi.h>
#include <accommon.h>


I tried finding the location of the above 2 header files but i couldn't find

**Comment by definiteprogress** [comment]
Got information from closed issue

**Comment by wichtounet** [comment]
I am glad you found the issue 👍
