### ISSUE TITLE
Qemu networking error

### ISSUE THREAD

**Issue by monstrous-moonshine** [wichtounet/thor-os#45]
Hi,

I'm running `make qemu` and getting the following error:
```
qemu-system-x86_64 -enable-kvm -cpu host -serial file:virtual.log -netdev tap,helper=/usr/lib/qemu/qemu-bridge-helper,id=thor_net0 -device rtl8139,netdev=thor_net0,id=thor_nic0 -vga std -hda hdd.img &
Reading kernel log (Ctrl+C for exit)
tail -f virtual.log
WARNING: Image format was not specified for 'hdd.img' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
failed to open /dev/net/tun: No such device
qemu-system-x86_64: -netdev tap,helper=/usr/lib/qemu/qemu-bridge-helper,id=thor_net0: bridge helper failed
```
(I edited the path to `qemu-bridge-helper` to point to where it resides in my Arch system. I also removed `sudo` because it doesn't seem to be required.) I can get it to run if I remove the `-netdev` and `-device` options, but then I guess the OS running inside Qemu won't have networking capabilities.

I believe there's some simple setting up of tap device that will solve this problem, but I found nothing by Googling. Could you help me out, please?

**Comment by wichtounet** [comment]
Hi

Have you tried with sudo? It seems to me that the default scripts from Qemu need root. 
If you do not have `/dev/net/tun`, you may also not have the necessary support in the kernel. What OS are you using?

**Comment by monstrous-moonshine** [comment]
@wichtounet Hi, thanks for your reply! I'm using Linux, and `/dev/net/tun` is present. The issue was that newer versions of Qemu need `script=no,downscript=no` to disable network configure and deconfigure scripts. Also, the `helper` option doesn't need to be passed in explicitly; Qemu is able to figure out the path to `qemu-bridge-helper`. With these changes, I was able to get Qemu to run!

**Comment by wichtounet** [comment]
Thanks for sharing, I am glad you made it work further!
