### ISSUE TITLE
make[1]: x86_64-elf-g++: No such file or directory

### ISSUE THREAD

**Issue by ahmeddsakrr** [wichtounet/thor-os#46]
![image](https://user-images.githubusercontent.com/91761423/203310794-2641eb4e-fc2b-4a75-8e92-e9509a0eab46.png)

done all the processes described in the build repo , but when I try to make the OS , this error occurs.

**Comment by wichtounet** [comment]
Did you succeed in building the OS?

**Comment by ahmeddsakrr** [comment]
> 

Yes , I did.
However , I have some questions.
Firstly is there a list of commands ?
Secondly is there a way to change the swiss keyboard to english one?
Sometime the OS starts and sometimes it does not , opens a black screen and nothing else , is there a solution for that?

**Comment by wichtounet** [comment]
Awesome, 

* Not really. The programs available are listed here: https://github.com/wichtounet/thor-os/tree/develop/programs
* The Swiss keyboard cannot be changed easily, only in code https://github.com/wichtounet/thor-os/blob/develop/kernel/src/drivers/keyboard.cpp
* I don't remember this problem last time I worked, I don't have a solution to it

Keep in mind that I have not worked on the project in several years.
