### ISSUE TITLE
Missing includes and minor changes

### ISSUE THREAD

**Issue by jdiego** [wichtounet/thor-os#5]
1. logging.hpp is missing at kernel/src/drivers/keyboard.cpp 
2. scheduler.hpp is missing at kernel/src/terminal.cpp
   In the makefile the command mkdosfs can be found at /sbin in some distros like ubuntu.

[ubuntu_compile_patch.txt](https://github.com/wichtounet/thor-os/files/454250/ubuntu_compile_patch.txt)

**Comment by wichtounet** [comment]
Hello, 

Thank you very much :) This should now be fixed in the develop branch. It seems I fucked up some includes recently. 

The next time, if you do a patch, don't hesitate to do a Pull Request so that I can apply it directly to the branch. 

Baptiste
