### ISSUE TITLE
Error compiling 

### ISSUE THREAD

**Issue by 112RG** [wichtounet/thor-os#8]
Hey this is a awesome project I was wondering if you could help me with compiling it I didn't really need to make the cross compiler since I use OSX that spits out 64-bit binaries but when I tried and build your operating system I get this `dd if=/dev/zero of=hdd.img bs=516096c count=1000
dd: bs: illegal numeric value
make: *** [hdd.img] Error 1`

I dont know what I am doing wrong here any ideas?

**Comment by wichtounet** [comment]
Hi, 

Glad you find the project interesting. 
Even if your compiler generates 64-bit binaries, you may need a cross compiler depending on what are the default options of your compiler regarding the platform. 

Regarding your problem, can you try with: 

dd if=/dev/zero of=hdd.img bs=516096 count=1000

(just remove the c after the bs=516096)

Maybe your version of dd does not support suffix. Since c basically says multiply by one, it's only being pedantic.

**Comment by 112RG** [comment]
Okay after correcting that now I get his 
`nasm -w+all -f bin -o stage1.bin stage1.asm
nasm: error: invalid option to `-w'
type `nasm -h' for help
make[1]: *** [stage1.bin] Error 1
make: *** [bootloader/stage1.bin] Error 2`

**Comment by wichtounet** [comment]
It seems you have very different tooling than I have. 

Can you post the result of `nasm -version` ?

If you want, you can remove the "-w+all" in the file bootloader/Makefile. This simply enables all warnings. 

I should remove the dependency to nasm in this file and use as directly.

**Comment by 112RG** [comment]
This is whatt i am using `NASM version 0.98.40 (Apple Computer, Inc. build 11) compiled on Feb 10 2016
`

**Comment by 112RG** [comment]
Okay I used my ubuntu machine and compiled the tool chain now when I compile I get this `make qemu
true
cd bootloader; make stage1.bin
make[1]: Entering directory '/home/rylee/thor-os/bootloader'
make[1]: 'stage1.bin' is up to date.
make[1]: Leaving directory '/home/rylee/thor-os/bootloader'
cd bootloader; make stage2.bin
make[1]: Entering directory '/home/rylee/thor-os/bootloader'
make[1]: 'stage2.bin' is up to date.
make[1]: Leaving directory '/home/rylee/thor-os/bootloader'
cd init; make
make[1]: Entering directory '/home/rylee/thor-os/init'
make[1]: Nothing to be done for 'default'.
make[1]: Leaving directory '/home/rylee/thor-os/init'
cd kernel; make
make[1]: Entering directory '/home/rylee/thor-os/kernel'
-e \x1b[31;01m[debug]\x1b[0m Compile \x1b[35;01msrc/interrupts.cpp\x1b[0m
In file included from ../tstl/include/string.hpp:12:0,
                 from include/print.hpp:15,
                 from src/interrupts.cpp:11:
../tstl/include/algorithms.hpp: In instantiation of 'void std::fill_n(ForwardIterator, size_t, const T&) [with ForwardIterator = void (**)(interrupt::syscall_regs*, void*); T = std::nullptr_t; typename std::enable_if<std::has_trivial_assign<typename std::iterator_traits<T>::value_type>::value, int>::type <anonymous> = 42; size_t = long unsigned int]':
src/interrupts.cpp:91:42:   required from here
../tstl/include/algorithms.hpp:192:8: error: converting to 'bool' from 'std::nullptr_t' requires direct-initialization [-fpermissive]
     if(!value){
        ^~~~~~
../tstl/include/algorithms.hpp: In instantiation of 'void std::fill_n(ForwardIterator, size_t, const T&) [with ForwardIterator = void**; T = std::nullptr_t; typename std::enable_if<std::has_trivial_assign<typename std::iterator_traits<T>::value_type>::value, int>::type <anonymous> = 42; size_t = long unsigned int]':
src/interrupts.cpp:92:46:   required from here
../tstl/include/algorithms.hpp:192:8: error: converting to 'bool' from 'std::nullptr_t' requires direct-initialization [-fpermissive]
Makefile:31: recipe for target 'debug/src/interrupts.cpp.o' failed
make[1]: *** [debug/src/interrupts.cpp.o] Error 1
make[1]: Leaving directory '/home/rylee/thor-os/kernel'
Makefile:6: recipe for target 'kernel/debug/kernel.bin' failed
make: *** [kernel/debug/kernel.bin] Error 2
`

**Comment by wichtounet** [comment]
This is indeed a very bad bug on my side :(
Sorry for all the inconvenience :cry:

This should be fixed now. 

Thank you for the testing :)

**Comment by 112RG** [comment]
Okay got way further down the line and another error at least the other one was fixed here is the compiler log http://pastebin.com/fVb42SqY
